---
title: "Lab 13: Missing Data"
author: "Fabio Setti"
institute: "PSYC 7804 - Regression with Lab"
bibliography: Additional files/R packages.bib
csl: Additional files/apa.csl
title-slide-attributes:
  data-transition: "zoom"
  data-visibility: "uncounted"
format:
   revealjs:
      footer: "Lab 13: Missing Data"
      width: 1280
      height: 720
      chalkboard: true
      slide-number: c/t 
      theme: Fabio_theme/Fabio_theme.scss
      navigation-mode: linear
      controls: false
      auto-stretch: false
      header-includes:
        - <script src="Fabio_theme/Fabio_theme.js"></script>

editor: source
---

## Today's Packages and Data 🤗


```{r}
dat <- rio::import("Data/employeecomplete.dat")[,-1]
dat_miss <- rio::import("Data/employee.dat")[,-1]


names(dat) <- c( "team", "turnover", "male", "empower", "lmx", "worksat", "climate", "cohesion")
names(dat_miss) <- c("team", "turnover", "male", "empower", "lmx", "worksat", "climate", "cohesion")
dat_miss[dat_miss == "999"] <- NA
```



## For all your missing data needs

This Lab is a very quick overview of some methods of dealing with missing data. More often than not, you will require 


## Missing data Mechanisms

There may be many reasons why you end up with missing data. In general, there are **3 mechanisms** that can describe the way in which data is missing:


:::: {.columns}
::: {.column width="30%"}

:::
::: {.column width="50%"}

:::
::::


```{r}

lav_mod <- "empower ~ lmx + worksat + climate + cohesion"

fit <- lavaan::sem(lav_mod, dat, meanstructure = TRUE, fixed.x = FALSE, missing = "fiml")

lavaan::summary(fit)
```


```{r}
library(VIM)
X.miss <- produce_NA(dat[, 5:8], proportion = 0.5)

dat_miss <- dat
dat_miss[,5:8] <- X.miss

fit_miss <- lavaan::sem(lav_mod, dat_miss, meanstructure = TRUE, fixed.x = TRUE, missing = "fiml")
lavaan::summary(fit_miss)

```

